---
title: "Prog Assignment"
author: "Mumin Mohamed"
date: "13 May 2020"
output: html_document
---


## 1.Plotting Histogram for Outcome
```{r }
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])
```

## 2. Best.R
```{r}
source("best.R")
best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
```
##3 Ranking Hospital within State
```{r}
source("rankhospital.R")
rankhospital("TX", "heart attack" , 4)
rankhospital("TX", "heart attack" , 5000)
rankhospital("TX", "heart attack" , "Best")
rankhospital("TX", "heart attack" , "Worst")
rankhospital("AL", "heart attack" , "Worst")
rankhospital("AL", "heart failure" , "Worst")
rankhospital("NY", "heart failure" , "Worst")
rankhospital("MA", "heart failure" , "Worst")
rankhospital("AK", "heart failure" , "Best")
rankhospital("AK", "heart failure" , 5)

```

